# Playbook to install and start Nginx on target nodes
- name: Install nginx
  hosts: nodes  # Target hosts (defined in inventory)
  become: true  # Root access required for package installation
  tasks:
    - name: Installing Nginx on nodes
      ansible.builtin.package:
        name: nginx  # Name of the package to install
        state: present  # Ensure Nginx is installed (installs if not present)

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx  # Specify the service name
        state: started  # Start Nginx if not already running
        enabled: true   # Enable Nginx to start on system boot


